config/routes.rb
Twi1::Application.routes.draw do |map|
  post "tweet/create"
  get "tweet/new"

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  root :to => "tweet#new"

end

app/models/tweet.rb
class Tweet
  def initialize(owner, text)
    @owner = owner
    @text = CGI.escapeHTML(text.to_s)
  end

  def save
    # FIXME: asynchronize each processes
    ([@owner] + @owner.followers).each do |u|
      add_a_tweet_on_timeline_to(u.username)
    end
    add_a_tweet_on_public_timeline()
  end

  def add_a_tweet_on_timeline_to(username)
    add_a_tweet_on_the_file("#{RAILS_ROOT}/public/#{username}.js")
  end

  def add_a_tweet_on_public_timeline()
    add_a_tweet_on_the_file("#{RAILS_ROOT}/public/_.js")
  end

  def add_a_tweet_on_the_file(file)
    File.open(file, 'r+') {|io|
      finale = "]);\n"
      io.seek(-finale.size, IO::SEEK_END)
      io.puts %|,{user: "#{@owner.username}", text: "#{@text}"}|
      io.write finale
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  after_create do
    File.open("#{RAILS_ROOT}/public/#{self.username}.js", 'w') {|io|
      io.puts 'timeline(['
      io.puts ']);'
    }
  end

  def followers
    # FIXME
    []
  end
end

app/models/user_session.rb
require 'rails/generators/generated_attribute'

class UserSession < Authlogic::Session::Base
  def to_key
    #new_record? ? ['a'] : [ self.send(self.class.primary_key) ]
    self.keys.to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  protect_from_forgery
  layout 'application'
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def new
    tmp = UserSession.find
    if tmp
      @user = tmp.user
    else
      redirect_to login_path
    end
  end

  def create
    user = UserSession.find.user
    Tweet.new(user, params[:tweets][:text]).save
    redirect_to '/tweet/new'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default("/")
    else
      render :action => 'new'
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to "/"
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'timeline' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweet/_public.html.erb
<h2>Public Timeline</h2>

<script type='text/javascript'>
  // copy from new.html.erb
  Event.observe(window, 'load', function() {
    var username = '_';
    var url = '/' + username + '.js?' + (new Date()).valueOf();
    var script = document.createElement('script');
    script.setAttribute('src', url);
    document.getElementsByTagName('head')[0].appendChild(script); 
  });
</script>

<div id='timeline'>loading...</div>

app/views/tweet/create.html.erb
<h1>Tweet#create</h1>
<p>Find me in app/views/tweet/create.html.erb</p>

app/views/tweet/new.html.erb
<h1>Tweet#new</h1>

<div align='right'>
  <%= link_to "Logout #{@user.username}", logout_path %>
</div>

<script type='text/javascript'>
  Event.observe(window, 'load', function() {
    var username = '<%= @user.username %>';
    var url = '/' + username + '.js?' + (new Date()).valueOf();
    var script = document.createElement('script');
    script.setAttribute('src', url);
    document.getElementsByTagName('head')[0].appendChild(script); 
  });
</script>

<%= form_for :tweets, :url => {:action => 'create'} do |f| %>
  <p>
  <%= f.text_field :text, :size => 50 %>
  </p>
  <p>
  <%= f.submit 'tweeeet' %>
  </p>
<% end %>

<div id='timeline'>loading...</div>

app/views/user_sessions/new.html.erb
<% title "Log in" %>

<p>Don't have an account? <%= link_to "Sign up!", signup_path %></p>

<%= form_for @user_session, :as => :user_session, :url => {:action => 'create'} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Log in" %></p>
<% end %>

<%= render :partial => 'tweet/public' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>